services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "rayen"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-boot-app:
    image: rayenkh98/thing2
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/rayen"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "pass"
      SERVER_PORT: "8089"
      SERVER_SERVLET_CONTEXT_PATH: "/tpfoyer"
    ports:
      - "8089:8089"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
