services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-boot-app:
    image: rayenkh98/devops
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: ""
      SERVER_PORT: "8089"
      SERVER_SERVLET_CONTEXT_PATH: "/tpfoyer"
    ports:
      - "8089:8089"
    depends_on:
       mysql:
          condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mysql-data: