apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: rayenkh98/tp-foyer
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/db?createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SERVER_PORT
              value: "8089"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/tpfoyer"
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: spring-boot-app
  type: LoadBalancer
