import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { FoyerService } from '../service/foyer.service'; // Import your service
import { Etudiant } from '../models/Etudiant'; // Import the Etudiant model

@Component({
  selector: 'app-add-etudiant',
  templateUrl: './add-etudiant.component.html',
  styleUrls: ['./add-etudiant.component.css']
})
export class AddEtudiantComponent {
  etudiantForm: FormGroup; // Form group for student
  loading: boolean = false; // Loading state
  error: string | null = null; // Error message

  constructor(
    private fb: FormBuilder,
    private foyerService: FoyerService,
    private router: Router
  ) {
    // Initialize the form group with validation
    this.etudiantForm = this.fb.group({
      nomEt: ['', Validators.required],
      prenomEt: ['', Validators.required],
      cin: [0, [Validators.required, Validators.min(1)]],
      ecole: ['', Validators.required],
      dateNaissance: [null, Validators.required]
    });
  }

  // Method to submit the form
  onSubmit(): void {
    if (this.etudiantForm.valid) {
      this.loading = true; // Start loading
      const newEtudiant: Etudiant = {
        idEtudiant: 0, // Assuming the ID will be generated by the server
        nomEt: this.etudiantForm.value.nomEt,
        prenomEt: this.etudiantForm.value.prenomEt,
        cin: this.etudiantForm.value.cin,
        ecole: this.etudiantForm.value.ecole,
        dateNaissance: this.etudiantForm.value.dateNaissance,
        reservations: [] // Initialize this based on your logic
      };

      // Call the service to add a new student
      this.foyerService.addEtudiant(newEtudiant).subscribe({
        next: () => {
          console.log('Chambre added successfully');
          this.etudiantForm.reset(); // Reset form after submission
        },
        error: (err) => {
          this.loading = false; // Stop loading
          this.error = 'Failed to add student. Please try again later.'; // Set error message
          console.error(err); // Log error for debugging
        }
      });
    }
  }
}
